// src/data/staticProducts.ts

export type StaticProduct = {
  id: string;
  name: string;
  brand?: string;
  category?: string;
  price: number;
  mrp?: number | null;
  image: string;
  alt?: string;
  rating?: number;
  reviewCount?: number;
  inStock?: boolean;
  shipsFast?: boolean;
  slug: string;
};

const StaticProducts: StaticProduct[][] = [
  [
    {
      id: "Agave Cactus Desert Ampoule",
      name: "Agave Cactus Desert Ampoule - 50ml",
      brand: "treeannsea",
      category: "skin-care",
      price: 832.5,
      mrp: null,
      image: "/images/Agave Cactus Desert Ampoule - 50ml.png",
      alt: "Lightweight hydrating ampoule with over 84% agave cactus extract to help lock in moisture even in dry conditions. With hyaluronic acid, ceramide, peptides and trehalose, it supports a dewy, balanced complexion. Helps soothe sensitivity and maintain the skin’s oil-water balance.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "agave-cactus-desert-ampoule",
    },
    {
      id: "Arctic Biome Hyaluron Toner",
      name: "Arctic Biome Hyaluron Toner - 200ml",
      brand: "treeannsea",
      category: "skin-care",
      price: 690.0,
      mrp: null,
      image: "/images/Arctic Biome Hyaluron Toner - 200ml - 1.jpg",
      alt: "Refreshing, alcohol-free toner inspired by Arctic purity to flood skin with hydration. Layers easily to prep skin between steps and leave it calm, bouncy and comfortable. Suitable for all skin types, especially dehydrated or sensitive.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "arctic-biome-hyaluron-toner",
    },
   
    {
      id: "Desert Rose Cream",
      name: "Desert Rose Cream - 50g",
      brand: "treeannsea",
      category: "skin-care",
      price: 882.0,
      mrp: null,
      image: "/images/Desert Rose Cream - 50g.png",
      alt: "Cushiony cream starring desert rose (Adenium) extract to nourish and improve elasticity. Absorbs quickly without greasiness while helping balance oil and moisture. Skin feels comfortably moisturized and smooth.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "desert-rose-cream",
    },
    {
      id: "Desert Salt Pack Cleanser",
      name: "Desert Salt Pack Cleanser - 150ml",
      brand: "treeannsea",
      category: "skin-care",
      price: 600.0,
      mrp: null,
      image: "/images/Desert Salt Pack Cleanser - 150ml.png",
      alt: "Multi-tasking salt cleanser that can be used as a 1-minute pack or a daily cleanser. Fine salt with konjac scrub gently polishes away dead skin while purifying pores. Rinses clean to leave skin soft, refreshed and hydrated.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "desert-salt-pack-cleanser",
    },
    {
      id: "Desert Salt Pack Cleanser 20ml",
      name: "Desert Salt Pack Cleanser - 20ml",
      brand: "treeannsea",
      category: "skin-care",
      price: 144.0,
      mrp: null,
      image: "/images/Desert Salt Pack Cleanser - 20ml.png",
      alt: "Travel-friendly size of the salt pack cleanser for on-the-go care. Use as a quick mask or gentle scrub to smooth and cleanse with fine salt + konjac. Leaves skin feeling clear and comfortable after rinse.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "desert-salt-pack-cleanser",
    },
     {
      id: "Sand Dune Desert Mist",
      name: "Sand Dune Desert Mist - 100ml",
      brand: "treeannsea",
      category: "skin-care",
      price: 729.0,
      mrp: null,
      image: "/images/Sand Dune Desert Mist - 100ml.png",
      alt: "Fine mist featuring desert rose extract (about 90%) to instantly replenish moisture. Pulullan forms a soft moisture veil to reduce stickiness and help makeup set. Leaves skin dewy and refreshed throughout the day.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "sand-dune-desert-mist",
    },
    {
      id: "SAND BALL THERAPY GUASHA",
      name: "SAND BALL THERAPY GUASHA - 159g",
      brand: "treeannsea",
      category: "skin-care",
      price: 1053.0,
      mrp: null,
      image: "/images/SAND BALL THERAPY GUASHA - 159g.png",
      alt: "Ergonomic ceramic gua sha massage tool designed to glide smoothly over the contours. Use with facial oil to relieve tension and encourage a lifted, refreshed look. Durable, easy-to-clean surface stays pleasantly cool on skin.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "sand-ball-therapy-guasha",
    },
    
    {
      id: "Arctic Biome Hyaluron Serum",
      name: "Arctic Biome Hyaluron Serum - 50ml",
      brand: "treeannsea",
      category: "skin-care",
      price: 562.5,
      mrp: null,
      image: "/images/Arctic Biome Hyaluron Serum - 50ml - 1.jpg",
      alt: "Fast-absorbing serum powered by an 8-layer hyaluronic acid complex and Arctic biome ferment. Restores moisture, reinforces the barrier and calms irritation for a plump look. Ideal for dry, sensitive or dehydrated skin.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "arctic-biome-hyaluron-serum",
    },
    {
      id: "Arctic Biome Hyaluron Cleansing gel",
      name: "Arctic Biome Hyaluron Cleansing gel - 150ml",
      brand: "treeannsea",
      category: "skin-care",
      price: 570.0,
      mrp: null,
      image: "/images/Arctic Biome Hyaluron Cleansing gel - 150ml - 1.jpg",
      alt: "Low-foam gel cleanser from the Arctic Biome line that gently lifts away impurities. Hydrating hyaluronic blend helps cleanse without stripping for a fresh, soft feel. Leaves the skin balanced and comfortable.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "arctic-biome-hyaluron-cleansing-gel",
    },
    {
      id: "Arctic Biome Hyaluron Cream",
      name: "Arctic Biome Hyaluron Cream - 50ml",
      brand: "treeannsea",
      category: "skin-care",
      price: 630.0,
      mrp: null,
      image: "/images/Arctic Biome Hyaluron Cream - 50ml - 1.jpg",
      alt: "Silky cream that seals in hydration with a hyaluronic complex and skin-barrier helpers. Melts in to cushion dryness, smooth texture and support a resilient barrier. Daily moisturizer for long-lasting, dewy comfort.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "arctic-biome-hyaluron-cream",
    },
    {
      id: "Signature Refresh Tamanu Oil",
      name: "Signature Refresh Tamanu Oil - 30ml",
      brand: "treeannsea",
      category: "skin-care",
      price: 882.0,
      mrp: null,
      image: "/images/Signature Refresh Tamanu Oil - 30ml - 1.png",
      alt: "A face oil blended with plant-based oils including tamanu to soothe and nourish. Helps protect from moisture loss and balance oil-water levels with continuous use. Leaves skin cushioned, calm and softly glowy.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "signature-refresh-tamanu-oil",
    },
    {
      id: "Madagascar Tamanu Oil original",
      name: "Madagascar Tamanu Oil original - 30ml",
      brand: "treeannsea",
      category: "skin-care",
      price: 787.5,
      mrp: null,
      image: "/images/Madagascar Tamanu Oil original - 30ml - 1.png",
      alt: "100% cold-pressed tamanu seed oil from Madagascar, rich in unsaturated fatty acids. Quick-absorbing oil that helps calm visible irritation and support the skin barrier. Can be used alone or mixed with moisturizer for extra nourishment.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "madagascar-tamanu-oil-original",
    },
    {
      id: "Madagascar Wild Centella Ampoule",
      name: "Madagascar Wild Centella Ampoule - 50ml",
      brand: "treeannsea",
      category: "skin-care",
      price: 447.0,
      mrp: null,
      image: "/images/Madagascar Wild Centella Ampoule - 50ml.png",
      alt: "Light, watery centella ampoule to calm redness and replenish hydration. Known to support a stronger skin barrier and soothe sensitive, irritated skin. Great for daily layering to keep skin clear and balanced.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "madagascar-wild-centella-ampoule",
    },
    {
      id: "Madagascar Wild Centella Ampoule 100ml",
      name: "Madagascar Wild Centella Ampoule - 100ml",
      brand: "treeannsea",
      category: "skin-care",
      price: 798.0,
      mrp: null,
      image: "/images/Madagascar Wild Centella Ampoule - 100ml.png",
      alt: "Light, watery centella ampoule to calm redness and replenish hydration. Known to support a stronger skin barrier and soothe sensitive, irritated skin. Great for daily layering to keep skin clear and balanced.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "madagascar-wild-centella-ampoule",
    },
    {
      id: "Madagascar Centella Vita C Toning Serum",
      name: "Madagascar Centella Vita C Toning Serum - 30ml",
      brand: "treeannsea",
      category: "skin-care",
      price: 862.5,
      mrp: null,
      image: "/images/Madagascar Centella Vita C Toning Serum - 30ml - 1.jpg",
      alt: "Brightening meets soothing: vitamin C works with centella to target dullness while staying gentle. Helps refine skin tone and texture without the stickiness. Made for everyday radiance on sensitive skin types.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "madagascar-centella-vita-c-toning-serum",
    },
    {
      id: "Madagascar CentellaTamanu Mask Pack 20ml 10EA/1SET",
      name: "Madagascar CentellaTamanu Mask Pack 20ml 10EA/1SET - 200ml",
      brand: "treeannsea",
      category: "skin-care",
      price: 891.0,
      mrp: null,
      image: "/images/Madagascar CentellaTamanu Mask Pack 20ml - 1.jpg",
      alt: "Sheet masks infused with centella and tamanu to hydrate and soothe tired skin. The essence helps calm sensitivity while leaving a moisturized, bouncy finish. A 10-sheet set for consistent weekly care.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "madagascar-centellatamanu-mask-pack-20ml-10ea-1set",
    },
    {
      id: "Bath Bomb Prism",
      name: "Bath Bomb Prism - 200g",
      brand: "treeannsea",
      category: "skin-care",
      price: 432.0,
      mrp: null,
      image: "/images/Bath Bomb Prism - 200g - 1.jpg",
      alt: "Fizzing bath bomb inspired by the ‘magic hour’ before sunset in Zadar—citrus and soft floral notes. Melts into warm water to relax the body and leave skin feeling soft. A luminous, mood-lifting soak for self-care nights.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "bath-bomb-prism",
    },
    {
      id: "Bath Bomb Capri",
      name: "Bath Bomb Capri - 200g",
      brand: "treeannsea",
      category: "skin-care",
      price: 432.0,
      mrp: null,
      image: "/images/Bath Bomb Capri - 200g - 1.jpg",
      alt: "Ocean-fresh bath bomb that echoes Capri’s sea caves with breezy, blue-toned notes. Dissolves to release a gentle aroma while softening and smoothing skin. A quick at-home escape for a refreshed, vacation-like soak.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "bath-bomb-capri",
    },

    {
      id: "Ampoule Gold",
      name: "Ampoule Gold",
      brand: "Pime",
      category: "skin-care",
      price: 3978.0,
      mrp: null,
      image: "/images/Pime_Feel_up_Ampoule_Gold_Skin_Care_Cosmetics_3.jpg",
      alt: "Radiance-boosting ampoule infused with gold flakes to brighten, firm and instantly revive dull skin.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "ampoule_gold",
    },
    {
      id: "Ampoule White",
      name: "Ampoule White",
      brand: "Pime",
      category: "skin-care",
      price: 3978.0,
      mrp: null,
      image: "/images/Pime_Feel_up_Ampoule_White_Skin_2ml.jpg",
      alt: "Brightening treatment ampoule that targets dark spots and uneven tone with a lightweight daily finish.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "ampoule_white",
    },
    {
      id: "Pime Remade Collagen Lotion",
      name: "Pime Remade Collagen Lotion",
      brand: "Pime",
      category: "skin-care",
      price: 2206,
      mrp: null,
      image: "/images/Pime Remade Collagen Lotion.jpg",
      alt: "Collagen-rich lotion that hydrates, plumps and smooths for a soft, bouncy complexion.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "pime_remade_collagen_lotion",
    },
    {
      id: "Pime Remade Serum",
      name: "Pime Remade Serum",
      brand: "Pime",
      category: "skin-care",
      price: 3442,
      mrp: null,
      image: "/images/Pime Remade Serum.png",
      alt: "Concentrated serum designed to improve elasticity and refine skin texture with daily use.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "pime_remade_serum",
    },
    {
      id: "Pime Remade Eye to Neck Cream",
      name: "Pime Remade Eye to Neck Cream",
      brand: "Pime",
      category: "skin-care",
      price: 2206,
      mrp: null,
      image: "/images/Pime Remade Eye to Neck Crnosm.png",
      alt: "Multi‑zone firming cream for delicate areas from eye to neck, smoothing fine lines and dryness.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "pime_remade_eye_to_neck_cream",
    },
    {
      id: "Pime Remade Sinbi Peel",
      name: "Pime Remade Sinbi Peel",
      brand: "Pime",
      category: "skin-care",
      price: 4400,
      mrp: null,
      image: "/images/Pime Remade Sinbi Peel.jpg",
      alt: "At‑home peeling care that gently exfoliates to reveal a smoother, brighter glow.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "pime_remade_sinbi_peel",
    },
    {
      id: "Snail Soothing Gel",
      name: "Snail Soothing Gel",
      brand: "Pime",
      category: "skin-care",
      price: 308,
      mrp: null,
      image: "/images/Snail Soothing Gel.jpg",
      alt: "Lightweight snail mucin gel that calms irritation and replenishes moisture without stickiness.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "snail_soothing_gel",
    },
    {
      id: "Pime Toneup Shower Cream",
      name: "Pime Toneup Shower Cream",
      brand: "Pime",
      category: "skin-care",
      price: 2206,
      mrp: null,
      image: "/images/Pime Toneup Shower Cream.jpg",
      alt: "Creamy body wash that brightens and softens skin for a fresh, even‑looking tone.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "pime_toneup_shower_cream",
    },
    {
      id: "Pime FeelUp B5 Vitamin Serum",
      name: "Pime FeelUp B5 Vitamin Serum",
      brand: "Pime",
      category: "skin-care",
      price: 1942,
      mrp: null,
      image: "/images/Pime FeelUp B5 Vitamin Serum.jpg",
      alt: "Barrier‑supporting serum with Vitamin B5 to deeply hydrate and reduce dryness and tightness.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "pime_feelUp_B5_vitamin_serum",
    },
    {
      id: "Pime Tea Tree Toner Pad",
      name: "Pime Tea Tree Toner Pad",
      brand: "Pime",
      category: "skin-care",
      price: 1324,
      mrp: null,
      image: "/images/Pime Tea Tree Toner Pad.jpg",
      alt: "Pre‑soaked toner pads with tea tree to clarify pores, smooth texture and calm blemish‑prone skin.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "pime_tea_tree_toner_pad",
    },
    {
      id: "Deeply Control Balancing Emulsion",
      name: "Deeply Control Balancing Emulsion - Moisturizing",
      brand: "Eleven Huesday",
      category: "skin-care",
      price: 3978.0,
      mrp: null,
      image: "/images/Deeply Control Balancing Emulsion - 1.jpg",
      alt: "Lightweight moisturizing emulsion that balances oil‑water levels for comfortable, dewy skin.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "deeply-control-balancing-emulsion",
    },
    {
      id: "Pinkberry Firming Sleep Mask",
      name: "Pinkberry Firming Sleep Mask - Moisturizing",
      brand: "Eleven Huesday",
      category: "skin-care",
      price: 3420.0,
      mrp: null,
      image: "/images/Pinkberry Firming Sleep Mask - 1.jpg",
      alt: "Overnight mask that firms and deeply hydrates so you wake up to bouncier, refreshed skin.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "pinkberry-firming-sleep-mask",
    },
    {
      id: "Face & Neck Sparkling Care Kit",
      name: "Face & Neck Sparkling Care Kit - Moisturizing",
      brand: "Eleven Huesday",
      category: "skin-care",
      price: 5850.0,
      mrp: null,
      image: "/images/Face & Neck Sparkling Care Kit - 1.jpg",
      alt: "Revitalizing face‑and‑neck kit designed to hydrate, brighten and smooth for a spa‑like glow.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "face-neck-sparkling-care-kit",
    },
    {
      id: "Skincteonic Recovery Serum",
      name: "Skincteonic Recovery Serum - Recovery",
      brand: "Eleven Huesday",
      category: "skin-care",
      price: 3240.0,
      mrp: null,
      image: "/images/Skintectonic Recovery Serum - 1.jpg",
      alt: "Barrier‑repair serum that soothes sensitivity and supports recovery after stress or treatments.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "skincteonic-recovery-serum",
    },
    {
      id: "Skincteonic Recovery Cream",
      name: "Skincteonic Recovery Cream - Recovery",
      brand: "Eleven Huesday",
      category: "skin-care",
      price: 3150.0,
      mrp: null,
      image: "/images/Skintectonic Recovery Cream - 1.jpg",
      alt: "Restorative cream that locks in moisture and helps reduce redness for soothed, resilient skin.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "skincteonic-recovery-cream",
    },
    {
      id: "Skincteonic C5 Soothing Mask",
      name: "Skincteonic C5 Soothing Mask - Recovery",
      brand: "Eleven Huesday",
      category: "skin-care",
      price: 2790.0,
      mrp: null,
      image: "/images/Skintectonic C5 Soothing Mask - 1.jpg",
      alt: "Comforting sheet mask that delivers calming hydration to restore balance and glow.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "skincteonic-c5-soothing-mask",
    },
    {
      id: "Cellspring Exo-Repair Ampoule",
      name: "Cellspring Exo-Repair Ampoule - Recovery",
      brand: "Eleven Huesday",
      category: "skin-care",
      price: 9900.0,
      mrp: null,
      image: "/images/Cellspring Exo-Repair Ampoule - 1.jpg",
      alt: "Intensive repair ampoule inspired by exosome science to support renewal and strengthen skin.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "cellspring-exo-repair-ampoule",
    },
    {
      id: "V-Renewal Bakuchiol Serum",
      name: "V-Renewal Bakuchiol Serum - Anti-Ageing",
      brand: "Eleven Huesday",
      category: "skin-care",
      price: 3600.0,
      mrp: null,
      image: "/images/V-Renewal Bakuchiol Serum - 1.jpg",
      alt: "Plant‑derived retinol alternative that smooths fine lines and refines texture with less irritation.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "v-renewal-bakuchiol-serum",
    },
    {
      id: "V-Renewal Bakuchiol Cream",
      name: "V-Renewal Bakuchiol Cream - Anti-Ageing",
      brand: "Eleven Huesday",
      category: "skin-care",
      price: 4230.0,
      mrp: null,
      image: "/images/V-Renewal Bakuchiol Cream - 1.jpgg",
      alt: "Nourishing anti‑ageing cream with bakuchiol to firm, smooth and support youthful bounce.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "v-renewal-bakuchiol-cream",
    },
    {
      id: "Despot Luminocity",
      name: "Despot Luminocity - Brightening & Radiance",
      brand: "Eleven Huesday",
      category: "skin-care",
      price: 3600.0,
      mrp: null,
      image: "/images/Despot Luminocity - 1.jpg",
      alt: "Glow‑boosting treatment that brightens dullness and revives tired‑looking skin.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "despot-luminocity",
    },
    {
      id: "Despot Exo-Bright Corrector",
      name: "Despot Exo-Bright Corrector - Brightening & Radiance",
      brand: "Eleven Huesday",
      category: "skin-care",
      price: 2880.0,
      mrp: null,
      image: "/images/Despot Exo-Bright Corrector - 1.jpg",
      alt: "Targeted brightening corrector to visibly reduce discoloration and improve overall clarity.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "despot-exo-bright-corrector",
    },
    {
      id: "Extra Clear Cream",
      name: "Extra Clear Cream - Brightening & Radiance",
      brand: "Eleven Huesday",
      category: "skin-care",
      price: 2340.0,
      mrp: null,
      image: "/images/Extra Clear Cream - 1.jpg",
      alt: "Daily brightening cream that smooths uneven texture and helps maintain a luminous finish.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "extra-clear-cream",
    },
    {
      id: "Extra Bright Peeling Gel",
      name: "Extra Bright Peeling Gel - Brightening & Radiance",
      brand: "Eleven Huesday",
      category: "skin-care",
      price: 1800.0,
      mrp: null,
      image: "/images/Extra Bright Peeling Gel - 1.jpg",
      alt: "Gentle peeling gel that lifts dead skin and impurities for instantly smoother, brighter skin.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "extra-bright-peeling-gel",
    },
    {
      id: "Deeply Control Balancing Toner",
      name: "Deeply Control Balancing Toner - Cleansing",
      brand: "Eleven Huesday",
      category: "skin-care",
      price: 2610.0,
      mrp: null,
      image: "/images/Deeply Control Balancing Toner - 1.jpg",
      alt: "Balancing toner that refines pores, removes residue and preps skin for the next steps.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "deeply-control-balancing-toner",
    },
    {
      id: "Pinkberry Cleansing Mist",
      name: "Pinkberry Cleansing Mist - Cleansing",
      brand: "Eleven Huesday",
      category: "skin-care",
      price: 2070.0,
      mrp: null,
      image: "/images/Pinkberry Cleansing Mist - 1.jpg",
      alt: "Refreshing cleansing mist that dissolves makeup and impurities for quick, on‑the‑go cleansing.",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "pinkberry-cleansing-mist",
    },
    {
      id: "prod_009",
      name: "Skin Barrier Glow Cover Cushion",
      brand: "CLIO",
      category: "Makeup",
      price: 1200,
      mrp: 1500,
      image: "/images/m-product-1.jpg",
      alt: "Skin Barrier Glow Cover Cushion",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "skin-barrier-glow-cover-cushion",
    },
    {
      id: "prod_010",
      name: "DOUBLE LONGWEAR COVER CONCEALER",
      brand: "CLIO",
      category: "Makeup",
      price: 424,
      mrp: 599,
      image: "/images/m-product-2.jpg",
      alt: "Double Longwear Cover Concealer",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "double-longwear-cover-concealer",
    },
    {
      id: "prod_011",
      name: "M Perfect Cover BB Cream SPF42/PA+++ 20ml",
      brand: "MISSHA",
      category: "Makeup",
      price: 520,
      mrp: 699,
      image: "/images/m-product-3.jpg",
      alt: "M Perfect Cover BB Cream",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "m-perfect-cover-bb-cream-spf42-pa-20ml",
    },
    {
      id: "prod_012",
      name: "Radiance Perfect-fit Cushion Foundation",
      brand: "HERA",
      category: "Makeup",
      price: 1152,
      mrp: 1499,
      image: "/images/m-product-4.jpg",
      alt: "Radiance Perfect-fit Cushion Foundation",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "radiance-perfect-fit-cushion-foundation",
    },
    {
      id: "prod_013",
      name: "SYRUPY TOK CHEEK",
      brand: "PERIPERA",
      category: "Makeup",
      price: 1140,
      mrp: 1399,
      image: "/images/m-product-5.jpg",
      alt: "SYRUPY TOK CHEEK",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "syrupy-tok-cheek",
    },
    {
      id: "prod_014",
      name: "ARTCLASS BY RODIN BLUSHER DE MAUVE",
      brand: "TOO COOL FOR SCHOOL",
      category: "Makeup",
      price: 1200,
      mrp: 1490,
      image: "/images/m-product-6.jpg",
      alt: "ARTCLASS BY RODIN BLUSHER DE MAUVE",
      rating: 4.6,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "artclass-by-rodin-blusher-de-mauve",
    },
    {
      id: "prod_015",
      name: "KILL COVER MESH GLOW CUSHION MINI SPF50+ PA++++",
      brand: "CLIO",
      category: "Makeup",
      price: 1170,
      mrp: 1490,
      image: "/images/m-product-7.jpg",
      alt: "KILL COVER MESH GLOW CUSHION MINI",
      rating: 4.4,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "kill-cover-mesh-glow-cushion-mini-spf50-pa",
    },
    {
      id: "prod_016",
      name: "PURE BLUSHED SUNSHINE CHEEK TTEOK RECIPE Collection",
      brand: "ROM&ND",
      category: "Makeup",
      price: 520,
      mrp: 699,
      image: "/images/m-product-8.jpg",
      alt: "PURE BLUSHED SUNSHINE CHEEK TTEOK RECIPE Collection",
      rating: 4.5,
      reviewCount: 0,
      inStock: true,
      shipsFast: true,
      slug: "pure-blushed-sunshine-cheek-tteok-recipe-collection",
    },
    {
      id: "prod_017",
      name: "Mothercare All We Know Baby Shampoo 300ml - Orange",
      brand: "Mothercare",
      category: "Baby",
      price: 292,
      mrp: null,
      image: "/images/baby-product-1.avif",
      alt: "Mothercare baby shampoo 300ml Orange",
      rating: 4.5,
      reviewCount: 4,
      inStock: true,
      shipsFast: true,
      slug: "mothercare-all-we-know-baby-shampoo-300ml-orange",
    },
    {
      id: "prod_018",
      name: "Bath Slime 480ml Bath All-in-One Wash",
      brand: "Bath Slime",
      category: "Baby",
      price: 800,
      mrp: null,
      image: "/images/baby-product-2.jpg",
      alt: "Bath Slime 480ml All-in-One Wash",
      rating: 4.5,
      reviewCount: 25,
      inStock: true,
      shipsFast: true,
      slug: "bath-slime-480ml-bath-all-in-one-wash",
    },
    {
      id: "prod_019",
      name: "Bath Slime 1+1 (480ml + 480ml) Bath All-in-One Wash",
      brand: "Bath Slime",
      category: "Baby",
      price: 2080,
      mrp: null,
      image: "/images/baby-product-3.jpg",
      alt: "Bath Slime 1+1 480ml All-in-One Wash",
      rating: 4.5,
      reviewCount: 2,
      inStock: true,
      shipsFast: true,
      slug: "bath-slime-1-plus-1-480ml-bath-all-in-one-wash",
    },
    {
      id: "prod_020",
      name: "Baby & Infant Creamy Essential Lotion 160ml",
      brand: "Baby & Infant",
      category: "Baby",
      price: 675,
      mrp: null,
      image: "/images/baby-product-4.jpg",
      alt: "Baby & Infant Creamy Essential Lotion 160ml",
      rating: 4.5,
      reviewCount: 30,
      inStock: true,
      shipsFast: true,
      slug: "baby-and-infant-creamy-essential-lotion-160ml",
    },
    {
      id: "prod_021",
      name: "Queensland Mineral Sun Cream 70ml",
      brand: "Queensland",
      category: "Baby",
      price: 800,
      mrp: null,
      image: "/images/baby-product-5.jpg",
      alt: "Queensland Mineral Sun Cream 70ml",
      rating: 4.5,
      reviewCount: 4,
      inStock: true,
      shipsFast: true,
      slug: "queensland-mineral-sun-cream-70ml",
    },
    {
      id: "prod_022",
      name: "Queensland Mineral Sun Cream Pact 15g",
      brand: "Queensland",
      category: "Baby",
      price: 1110,
      mrp: null,
      image: "/images/baby-product-6.jpg",
      alt: "Queensland Mineral Sun Cream Pact 15g",
      rating: 4.5,
      reviewCount: 25,
      inStock: true,
      shipsFast: true,
      slug: "queensland-mineral-sun-cream-pact-15g",
    },
    {
      id: "prod_023",
      name: "Baby Bubble Bottom Cleanser 300ml",
      brand: "Baby Bubble",
      category: "Baby",
      price: 800,
      mrp: null,
      image: "/images/baby-product-7.jpg",
      alt: "Baby Bubble Bottom Cleanser 300ml",
      rating: 4.5,
      reviewCount: 2,
      inStock: true,
      shipsFast: true,
      slug: "baby-bubble-bottom-cleanser-300ml",
    },
    {
      id: "prod_024",
      name: "Bath Slime Pink 480ml",
      brand: "Bath Slime",
      category: "Baby",
      price: 800,
      mrp: null,
      image: "/images/baby-product-8.jpg",
      alt: "Bath Slime Pink 480ml",
      rating: 4.5,
      reviewCount: 30,
      inStock: true,
      shipsFast: true,
      slug: "bath-slime-pink-480ml",
    },

    {
      id: "Medi Water M7 500ml",
      name: "Medi Water M7 500ml",
      brand: " ",
      category: "Life & Home",
      price: 117,
      mrp: null,
      image: "/images/medi water.png",
      alt: "It is a FDA-approved mixed drink product that contains 'Levan', a new natural bio material, in purified water. It's a fragrance-free product that makes it easier to get prebiotics in your daily life.",
      rating: 4.5,
      reviewCount: 4,
      inStock: true,
      shipsFast: true,
      slug: "medi_water_m7_500ml",
    },
    {
      id: "Portable Eco-Friendly Water Mist Sprayer",
      name: "Portable Eco-Friendly Water Mist Sprayer",
      brand: " ",
      category: "Life & Home",
      price: 80000,
      mrp: null,
      image: "/images/sparyer.png",
      alt: "Portable Eco-Friendly Water Mist Sprayer is a next-generation solution for refreshing and caring for your environment—at home, in the garden, or on the go. Powered by advanced plasma technology, this device transforms ordinary tap water into a fine, refreshing mist without the need for any added chemicals. This makes it a safe and sustainable choice for a variety of everyday uses.",
      rating: 4.5,
      reviewCount: 4,
      inStock: true,
      shipsFast: true,
      slug: "portable_eco_friendly_water_mist_sprayer",
    },
    {
      id: "prod_025",
      name: "Samyang Hot Chicken Ramen Cheese Noodles, 5 × 140 g",
      brand: "Samyang",
      category: "Life & Home",
      price: 549,
      mrp: null,
      image: "/images/Samyang Buldak FIRE CHICKEN (Pack of 5) 5 × 140 g.png",
      alt: "Samyang Hot Chicken Ramen Cheese 5 pack",
      rating: 4.5,
      reviewCount: 4,
      inStock: true,
      shipsFast: true,
      slug: "samyang-hot-chicken-ramen-cheese-noodles-5x140g",
    },
    {
      id: "prod_026",
      name: "Samyang Buldak Carbonara Ramen, Pack of 5 (650 g)",
      brand: "Samyang",
      category: "Life & Home",
      price: 559,
      mrp: null,
      image: "/images/Samyang Buldak Carbonara Ramen, Pack of 5 (650 g).png",
      alt: "Samyang Buldak Carbonara 5 pack",
      rating: 4.5,
      reviewCount: 25,
      inStock: true,
      shipsFast: true,
      slug: "samyang-buldak-carbonara-ramen-pack-of-5-650g",
    },
    // {
    //   id: "prod_027",
    //   name: "Samyang Buldak FIRE CHICKEN (Pack of 5) 5 × 140 g",
    //   brand: "Samyang",
    //   category: "Life & Home",
    //   price: 615,
    //   mrp: null,
    //   image: "/images/life-p-3.webp",
    //   alt: "Samyang Buldak Fire Chicken 5 pack",
    //   rating: 4.5,
    //   reviewCount: 2,
    //   inStock: true,
    //   shipsFast: true,
    //   slug: "samyang-buldak-fire-chicken-pack-of-5-5x140g",
    // },
    {
      id: "prod_028",
      name: "Samyang Buldak Ramen Noodles – 2X Spicy, 140 g",
      brand: "Samyang",
      category: "Life & Home",
      price: 140,
      mrp: null,
      image: "/images/Samyang Buldak Ramen Noodles – 2X Spicy, 140 g.png",
      alt: "Samyang Buldak 2X Spicy 140g",
      rating: 4.5,
      reviewCount: 30,
      inStock: true,
      shipsFast: true,
      slug: "samyang-buldak-ramen-noodles-2x-spicy-140g",
    },
    {
      id: "prod_029",
      name: "Samyang Cheese Buldak Hot Chicken Flavor Ramen Cup, 70 g",
      brand: "Samyang",
      category: "Life & Home",
      price: 135,
      mrp: null,
      image: "/images/Samyang Cheese Buldak Hot Chicken Flavor Ramen Cup, 70 g.png",
      alt: "Samyang Cheese Buldak Cup 70g",
      rating: 4.5,
      reviewCount: 4,
      inStock: true,
      shipsFast: true,
      slug: "samyang-cheese-buldak-hot-chicken-flavor-ramen-cup-70g",
    },
    {
      id: "prod_030",
      name: "Samyang Carbonara Buldak Ramen Cup, 80 g",
      brand: "Samyang",
      category: "Life & Home",
      price: 135,
      mrp: null,
      image: "/images/Samyang Carbonara Buldak Ramen Cup, 80 g.png",
      alt: "Samyang Carbonara Buldak Cup 80g",
      rating: 4.5,
      reviewCount: 25,
      inStock: true,
      shipsFast: true,
      slug: "samyang-carbonara-buldak-ramen-cup-80g",
    },
    {
      id: "prod_031",
      name: "Samyang Buldak – Hot Chicken Flavor Sauce, 200 g",
      brand: "Samyang",
      category: "Life & Home",
      price: 495,
      mrp: null,
      image: "/images/Samyang Buldak – Hot Chicken Flavor Sauce, 200 g.png",
      alt: "Samyang Buldak Hot Chicken Flavor Sauce 200g",
      rating: 4.5,
      reviewCount: 2,
      inStock: true,
      shipsFast: true,
      slug: "samyang-buldak-hot-chicken-flavor-sauce-200g",
    },
    // {
    //   id: "prod_032",
    //   name: "Samyang Buldak Instant Ramen – 3X Spicy, 140 g Pouch",
    //   brand: "Samyang",
    //   category: "Life & Home",
    //   price: 150,
    //   mrp: null,
    //   image: "/images/life-p-9.webp",
    //   alt: "Samyang Buldak 3X Spicy 140g Pouch",
    //   rating: 4.5,
    //   reviewCount: 30,
    //   inStock: true,
    //   shipsFast: true,
    //   slug: "samyang-buldak-instant-ramen-3x-spicy-140g-pouch",
    // },
  ],
];

export default StaticProducts;
