// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gquqttucpemzxfybwtud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxdXF0dHVjcGVtenhmeWJ3dHVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1ODQ4OTksImV4cCI6MjA3MTE2MDg5OX0.joWWDw6Fn9YhCiwIGNFvyK2H-J3glumP5-d07v-drNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});